run:
  tests: true
  allow-parallel-runners: true
  timeout: 5m

# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - dupl
    - errorlint
    - funlen
    - errcheck
    - gofmt
    - goconst
    - gofumpt
    - gocyclo
    - godox
    - gosec
    - gocritic
    - govet
    - goimports
    - goheader
    - misspell
    - nolintlint
    - revive
    - stylecheck
    - tparallel
    - tagliatelle
    - unconvert
    - unparam
    - whitespace
    - nilerr

linters-settings:
  dupl:
    # Tokens count to trigger issue.
    # Default: 150
    threshold: 100

  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors.
    # Default: true
    asserts: false

  funlen:
    # Checks the number of lines in a function.
    # Default: 60
    lines: -1
    # Default: 40
    statements: 50
    # Ignore comments when counting lines.
    # Default false
    ignore-comments: true

  goconst:
    # Minimal length of string constant.
    # Default: 3
    min-len: 2
    # Default: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint

  gocyclo:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 15

  godox:
    keywords:
      - FIXME
      - TODO
      - FIX
      - NOTE
      - OPTIMIZE # marks code that should be optimized before merging
      - HACK # marks hack-around that should be removed before merging

  gofmt:
    # Simplify code: gofmt with `-s` option.
    # Default: true
    simplify: false
    # Apply the rewrite rules to the source before reformatting.
    # https://pkg.go.dev/cmd/gofmt
    # Default: []
    rewrite-rules:
      # - pattern: 'interface{}'
      #   replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'

  goimports:
    local-prefixes: github.com/golangci/golangci-lint

  govet:
    enable-all: true
    disable:
      - fieldalignment

  misspell:
    # Correct spellings using locale preferences for US or UK.
    locale: US

  nolintlint:
    # Disable to ensure that all nolint directives actually have an effect.
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped

  revive:
    rules:
      - name: indent-error-flow
      - name: unexported-return
        disabled: true
      - name: unused-parameter
      - name: unused-receiver

issues:
  exclude-rules:
    - path: (.+)_test\.go
      linters:
        - dupl
        - mnd
        - lll

    # Deprecated linter options.
    - path: pkg/golinters/errcheck/errcheck.go
      linters: [staticcheck]
      text: "SA1019: errCfg.Exclude is deprecated: use ExcludeFunctions instead"
    - path: pkg/golinters/errcheck/errcheck.go
      linters: [staticcheck]
      text: "SA1019: errCfg.Ignore is deprecated: use ExcludeFunctions instead"
    - path: pkg/golinters/govet/govet.go
      linters: [staticcheck]
      text: "SA1019: cfg.CheckShadowing is deprecated: the linter should be enabled inside Enable."
    - path: pkg/golinters/godot/godot.go
      linters: [staticcheck]
      text: "SA1019: settings.CheckAll is deprecated: use Scope instead"
    - path: pkg/goformatters/gci/gci.go
      linters: [staticcheck]
      text: "SA1019: settings.LocalPrefixes is deprecated: use Sections instead."

    # Related to `run.go`, it cannot be removed.
    - path: pkg/golinters/gofumpt/gofumpt.go
      linters: [staticcheck]
      text: "SA1019: settings.LangVersion is deprecated: use the global `run.go` instead."

    # Based on existing code, the modifications should be limited to make maintenance easier.
    - path: pkg/golinters/unused/unused.go
      linters: [gocritic]
      text: "rangeValCopy: each iteration copies 160 bytes \\(consider pointers or indexing\\)"

    # Related to the result of computation but divided multiple times by 1024.
    - path: test/bench/bench_test.go
      linters: [gosec]
      text: "G115: integer overflow conversion uint64 -> int"

  exclude-dirs:
    - test/testdata_etc # test files
    - internal/go # extracted from Go code
    - internal/x # extracted from x/tools code
  exclude-files:
    - pkg/goanalysis/runner_checker.go # extracted from x/tools code
