version: "2"
run:
  tests: true
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - dupl
    - errcheck
    - errorlint
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gosec
    - govet
    - misspell
    - nilerr
    - nolintlint
    - revive
    - staticcheck
    - tagliatelle
    - tparallel
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 100
    errorlint:
      asserts: false
    funlen:
      lines: -1
      statements: 50
      ignore-comments: true
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - FIXME
        - TODO
        - FIX
        - NOTE
        - OPTIMIZE
        - HACK
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    revive:
      rules:
        - name: indent-error-flow
        - name: unexported-return
          disabled: true
        - name: unused-parameter
        - name: unused-receiver
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - lll
          - mnd
        path: (.+)_test\.go
      - linters:
          - staticcheck
        path: pkg/golinters/errcheck/errcheck.go
        text: 'SA1019: errCfg.Exclude is deprecated: use ExcludeFunctions instead'
      - linters:
          - staticcheck
        path: pkg/golinters/errcheck/errcheck.go
        text: 'SA1019: errCfg.Ignore is deprecated: use ExcludeFunctions instead'
      - linters:
          - staticcheck
        path: pkg/golinters/govet/govet.go
        text: 'SA1019: cfg.CheckShadowing is deprecated: the linter should be enabled inside Enable.'
      - linters:
          - staticcheck
        path: pkg/golinters/godot/godot.go
        text: 'SA1019: settings.CheckAll is deprecated: use Scope instead'
      - linters:
          - staticcheck
        path: pkg/goformatters/gci/gci.go
        text: 'SA1019: settings.LocalPrefixes is deprecated: use Sections instead.'
      - linters:
          - staticcheck
        path: pkg/golinters/gofumpt/gofumpt.go
        text: 'SA1019: settings.LangVersion is deprecated: use the global `run.go` instead.'
      - linters:
          - gocritic
        path: pkg/golinters/unused/unused.go
        text: 'rangeValCopy: each iteration copies 160 bytes \(consider pointers or indexing\)'
      - linters:
          - gosec
        path: test/bench/bench_test.go
        text: 'G115: integer overflow conversion uint64 -> int'
    paths:
      - pkg/goanalysis/runner_checker.go
      - test/testdata_etc
      - internal/go
      - internal/x
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: a[b:len(a)]
          replacement: a[b:]
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - pkg/goanalysis/runner_checker.go
      - test/testdata_etc
      - internal/go
      - internal/x
      - third_party$
      - builtin$
      - examples$
